Mock: RabbitMQ
Rabbit:
  Host: localhost
  Port: 5672
  User: guest
  Password: guest
  RequestQueue: q.retrieval
  ResponseQueue: q.response
Mode: responder
Response:
  File: ./response_short.json
  Amount: 1