ConnectThrough: RabbitMQ
Rabbit:
  Host: localhost
  Port: 5672
  User: guest
  Password: guest
  Exchanges: 
    - Exchange: 
      Name: ex.response
      RoutingKey: "responses.#"
  Queues: 
    - Queue:
      Name: q.response
      Args:
        - "x-message-ttl": 300000
        - "x-queue-mode": "lazy"
    - Queue:
      Name: q.test
  ConnectionRetry:
    ElapsedTime: 2
    Interval: 20
Mode: receiver
Responses:
  - Response:
    To: "ex.response"
    Request:
      To: "q.retrieval"
    Body:
      File: ./response_short.json
    Options:
      Quantity: 10
      Delay: 200
  - Response:
    To: "ex.response"
    Request:
      To: "q.test"
      Matchers:
        Contains: 
          Value: "\"systemId\": 999"
    Body:
      String: "plain response"
    Options:
      Quantity: 1
Request:
  File: ./request.json
  Options:
    Delay: 0
    Quantity: 1