ConnectThrough: RabbitMQ
Rabbit:
  Host: localhost
  Port: 5672
  User: guest
  Password: guest
  Exchanges: 
    - Exchange: 
      Name: ex.response
      RoutingKey: "responses.#"
    - Exchange: 
      Name: test-sender-requests
  Queues: 
    - Queue:
      Name: q.retrieval
      # Args:
      #   - "x-message-ttl": 300000
      #   - "x-queue-mode": "lazy"
    - Queue:
      Name: q.test
  ConnectionRetry:
    ElapsedTime: 2
    Interval: 20
Mode: receiver
Responses:
  - Response:
    To: "ex.response"
    Request:
      To: "q.retrieval"
      Match: all
      Matchers:
      - Type: contains
        In: body
        Value: "requestId"
      - Type: contains
        In: body
        Value: "systemId"
    Body:
      File: ./response_short.json
    Options:
      Quantity: 10
      Delay: 200
  - Response:
    To: "ex.response"
    Request:
      To: "q.test"
      Match: any
      Matchers:
        - Type: contains
          In: body 
          Value: "\"systemId\": 999"
        - Type: contains
          In: body 
          Value: "test"
    Body:
      String: "plain response"
    Options:
      Quantity: 1
Requests:
  - Request:
    To: "test-sender-requests"
    From: "q.test"
    Body:
      File: ./request.json
    Options:
      Quantity: 1