ConnectThrough: HTTP
HTTP:
  Serve:              # This is where we will host in case macaw works as a receiver
    Host: localhost
    Port: 1234
    Secured: false    # Big question mark here
  Remote:             # This is where we will send requests in case macaw works as sender
    Host: localhost
    Port: 4321
    Secured: false # Big question mark here
Mode: receiver
Responses:
  # Build: for request with field("requestID") equals(2) respond with file("response_failed.json")
  # Build: for request like file("request.json") on endpoint("/evaluate") respond with file("response_short.json")
  # Build: for request on endpoint("/health") respond with content("{"status":"ok"}")
  - Response:
    Request:
      To: "/test"
    Body:
      File: ./response_short.json
    Options:
      Quantity: 1
      Delay: 200
  - Response:
    Request:
      To: "/test/evaluate"
      Matchers:
        Contains: 
          Value: "\"systemId\": 999"
    Body:
      String: "plain response"
    Options:
      Quantity: 1
Request:
  - Request:
    To: "/application/events"
    Body:
      File: ./request.json
    Options:
      Quantity: 10
  - Request:
    To: "/application/register"
    Body:
      String: "{\"form\": \"test\"}"
    Headers:
      - Parameter:
        Name: "Content-Type"
        Value: "application/json"
    Parameters: 
      - Parameter:
        Name: "id"
        Value: "10"
      - Parameter: 
        Name: "persistent"
        Value: "false"
    Options:
      Delay: 10000
  # Build: send request to endpoint("/application/events") with body from file("request.json")