Admin:
  Enabled: true
  Port: 1235
ConnectThrough: HTTP
DumpMetrics:
  Enabled: true
  Frequency: 5
HTTP:
  Serve: 
    Host: /test
    Port: 1234
Mode: receiver
Responses:
  - Response:
    Request:
      To: "/test"
      Matchers:
        - Type: field
          In: headers
          Name: "requestId"
          Value: 999
    Body:
      String: 
      - "HTTP/1.1 400 Bad Request\r\nContent-Length: 0\r\n\r\n"
      - "HTTP/1.1 403 Forbidden\r\nContent-Length: 0\r\n\r\n"
      - "HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\n\r\n"
    Options: 
      Quantity: 1
      RandomDelay:
        Min: 0s
        Max: 2s
  - Response:
    Request:
      To: "/test"
      Matchers:
      - Type: excludesfield
        In: headers
        Name: "requestId"
        Value: 10
    Body:
      File: ./response_short_http.json
    Options: 
      Quantity: 1
      Delay: 300ms
  - Response:
    Request:
      To: "/otherTest"
      Matchers:
        - Type: field
          In: headers
          Name: "otherRequestId"
          Value: 10
    Body:
      File: ./response_short_http_other.json
    Options: 
      Quantity: 1
  - Response:
    Alias: "deadLetter"
    Request:
      To: "/otherTest"
      Matchers:
        - Type: fieldcontains
          In: headers
          Name: "deadLetter"
          Value: "fwd"
    Body:
      String: "Forwarding to the dead letter queue"
    Options: 
      Quantity: 1
Request:
  Body:
    File: ./request.json
  Options: 
    Delay: 0
    Quantity: 1
