ConnectThrough: HTTP
HTTP:
  Serve: 
    Host: /test
    Port: 1234
Mode: receiver
Responses:
  - Response:
    Request:
      To: "/test"
    Body:
      File: ./response_short_http.json
    Options: 
      Quantity: 1
  - Response:
    Request:
      To: "/otherTest"
      Matchers:
        Field: 
          Name: "otherRequestId"
          Value: 10
    Body:
      File: ./response_short_http_other.json
    Options: 
      Quantity: 1
Request:
  Body:
    File: ./request.json
  Options: 
    Delay: 0
    Quantity: 1
