ConnectThrough: RabbitMQ
Rabbit:
  Host: localhost
  Port: 5672
  User: guest
  Password: guest
  ResponseExchange: q.response
  RequestQueue: q.retrieval
  ResponseQueue: q.response
  ConnectionRetry:
    ElapsedTime: 2
    Interval: 20
Mode: receiver
Responses:
  - Response:
    Request:
      To: "q.response"
    File: ./response_short_http.json
    Amount: 10
Request:
  File: ./request.json
  Delay: 0
  Amount: 1