ConnectThrough: RabbitMQ
Rabbit:
  Host: localhost
  Port: 5672
  User: guest
  Password: guest
  Exchanges: 
    - Exchange: 
      Name: ex.response
      RoutingKey: "responses.#"
  Queues: 
    - Queue:
      Name: q.response
      Args:
        - "x-message-ttl": 300000
        - "x-queue-mode": "lazy"
    - Queue:
      Name: q.test
  ConnectionRetry:
    ElapsedTime: 2
    Interval: 20
Mode: receiver
Responses:
  - Response:
    To: "ex.response"
    Request:
      To: "q.retrieval"
    File: ./response_short.json
    Amount: 10
    Delay: 200
  - Response:
    To: "ex.response"
    Request:
      To: "q.test"
      Contains: 
        Value: "\"systemId\": 999"
    String: "plain response"
    Amount: 1
Request:
  File: ./request.json
  Delay: 0
  Amount: 1