ConnectThrough: HTTP
HTTP:
  Serve: 
    Host: /test
    Port: 1234
Mode: receiver
Responses:
  - Response:
    Request:
      To: "/test"
    File: ./response_short_http.json
    Amount: 1
  - Response:
    Request:
      To: "/otherTest"
      Field: 
        Name: "otherRequestId"
        Value: 10
    File: ./response_short_http_other.json
    Amount: 1
Request:
  File: ./request.json
  Delay: 0
  Amount: 1